/*
 * Copyright (c) Huawei Technologies Co., Ltd. 2026. All rights reserved.
 */

package com.huawei.cloudsop.genui.core.validation.interception;

import static org.junit.jupiter.api.Assertions.assertTrue;

import com.huawei.cloudsop.genui.core.contract.GenerationContract;
import com.huawei.cloudsop.genui.core.llm.protocol.ChatMessage;
import com.huawei.cloudsop.genui.core.validation.ValidationIssue;
import com.huawei.cloudsop.genui.core.validation.ValidationResult;
import com.huawei.cloudsop.genui.core.validation.repair.ReaskPromptBuilder;

import org.junit.jupiter.api.Test;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.util.List;
import java.util.Map;

/**
 * Acceptance artifact generator (design Decision 11.5): dumps every corpus case as DSL → full validator issues → the
 * reask prompt the repair model would actually see (post cascade suppression). Reviewing
 * {@code target/interception-corpus-dump.md} after any hint/prompt change is the fastest way to judge
 * repair-friendliness case by case. The output is a build artifact — never commit it.
 *
 * @since 2026
 */
class InterceptionCorpusDumpTest {

    private static final Path OUTPUT = Path.of("target", "interception-corpus-dump.md");

    @Test
    void dumpCorpusPromptView() throws IOException {
        StringBuilder md = new StringBuilder();
        md.append("# Interception corpus — prompt view dump\n\n");
        md.append("Generated by `InterceptionCorpusDumpTest`; build artifact, do not commit.\n");
        md.append("Issues show the FULL validator output; the prompt section shows what survives\n");
        md.append("cascade suppression in `ReaskPromptBuilder`.\n");

        for (Map<String, Object> testCase : InterceptionCorpusTest.cases()) {
            String id = InterceptionCorpusTest.str(testCase.get("id"));
            String dsl = InterceptionCorpusTest
                    .read("interception-corpus/" + InterceptionCorpusTest.str(testCase.get("dslFile")));
            GenerationContract contract = InterceptionCorpusTest
                    .loadContract(InterceptionCorpusTest.str(testCase.get("contractFile")));
            ValidationResult result = InterceptionCorpusTest.validate(testCase);

            md.append("\n---\n\n## ").append(id);
            md.append(" (").append(InterceptionCorpusTest.str(testCase.get("expectedClass"))).append(", ");
            md.append(InterceptionCorpusTest.str(testCase.get("expectedOutcome"))).append(")\n");
            md.append("\n### DSL\n\n```\n").append(dsl.strip()).append("\n```\n");

            md.append("\n### Validator issues (full)\n\n");
            if (result.issues().isEmpty()) {
                md.append("(none)\n");
            } else {
                for (ValidationIssue issue : result.issues()) {
                    md.append("- ").append(issue.severity()).append(" [").append(issue.code()).append("] ")
                            .append(issue.message()).append(" stmt=").append(issue.statementId()).append(" line=")
                            .append(issue.line()).append(':').append(issue.column());
                    if (issue.hint() != null) {
                        md.append("\n  hint: ").append(issue.hint());
                    }
                    md.append('\n');
                }
            }

            List<ChatMessage> messages = ReaskPromptBuilder.buildFullRepair(null, dsl, result.issues(), contract);
            md.append("\n### Reask prompt (system, post-suppression)\n\n```\n")
                    .append(messages.get(0).content().strip()).append("\n```\n");
        }

        Files.createDirectories(OUTPUT.getParent());
        Files.writeString(OUTPUT, md.toString(), StandardCharsets.UTF_8);
        assertTrue(Files.size(OUTPUT) > 0, "dump artifact written to " + OUTPUT);
    }
}
