root = Stack([header, tabs])
header = CardHeader("Interface Bandwidth Metrics", "Top interfaces by input and output byte rate")
inputGroup = data.queryInterfaceMetrics[0]
outputGroup = data.queryInterfaceMetrics[1]
inputData = inputGroup.telemetryData
outputData = outputGroup.telemetryData
tabs = Tabs([inputTab, outputTab])
inputTab = TabItem("input", "Input Bandwidth", [inputCard])
outputTab = TabItem("output", "Output Bandwidth", [outputCard])
inputCard = Card([inputHeader, inputTable])
inputHeader = CardHeader("Top Input Interfaces", "Byte rate (B/s)")
inputTable = Table([inputNameCol, inputRateCol, inputDeviceCol], inputData)
inputNameCol = Col("Interface", "ifName")
inputRateCol = Col("Byte Rate", "input_byte_rate", {cell: @Render("v", TextContent(@FormatBytes(v)))})
inputDeviceCol = Col("Device", "neName")
outputCard = Card([outputHeader, outputTable])
outputHeader = CardHeader("Top Output Interfaces", "Byte rate (B/s)")
outputTable = Table([outputNameCol, outputRateCol, outputDeviceCol], outputData)
outputNameCol = Col("Interface", "ifName")
outputRateCol = Col("Byte Rate", "output_byte_rate", {cell: @Render("v", TextContent(@FormatBytes(v)))})
outputDeviceCol = Col("Device", "neName")
