root = Stack([header, kpiRow, tabs], "column", "m")
header = CardHeader(data.deviceName + " (" + data.deviceIp + ")", "Fabric: " + data.fabricName)
kpiRow = Stack([linkKpi, opticalKpi], "row", "m", "stretch", "start", false)
linkKpi = Card([TextContent("Total Links", "small"), TextContent("" + data.linkCount, "large-heavy")])
opticalKpi = Card([TextContent("Optical Modules", "small"), TextContent("" + data.opticalCount, "large-heavy")])
tabs = Tabs([linksTab, modulesTab])
linksTab = TabItem("links", "Links (" + data.linkCount + ")", [linksCard])
modulesTab = TabItem("modules", "Optical Modules (" + data.opticalCount + ")", [modulesCard])
linksCard = Card([CardHeader("Link Details", "Active connections"), linksTable])
linksTable = Table([linkNameCol, aPortCol, zPortCol, aNeCol, zNeCol, rateCol, typeCol, statusCol], data.links)
linkNameCol = Col("Link Name", "linkName")
aPortCol = Col("A-Port", "aPortName")
zPortCol = Col("Z-Port", "zPortName")
aNeCol = Col("A-NE", "aNeName")
zNeCol = Col("Z-NE", "zNeName")
rateCol = Col("Rate", "layerRate")
typeCol = Col("Type", "linkType")
statusCol = Col("Status", "linkStatus", {cell: @Render("v", v == "在线" ? Tag("Online", "success") : Tag("Offline", "danger"))})
modulesCard = Card([CardHeader("Optical Module Inventory", "Transceiver details"), modulesTable])
modulesTable = Table([snCol, vendorCol, typeCol2, ifNameCol, adminCol, operCol, certCol], data.opticalModules)
snCol = Col("SN", "opticalSn")
vendorCol = Col("Vendor", "opticalVendor")
typeCol2 = Col("Transceiver Type", "transType")
ifNameCol = Col("Interface", "ifName")
adminCol = Col("Admin Status", "adminStatus", {cell: @Render("v", v == "Up" ? Tag("Up", "success") : Tag("Down", "danger"))})
operCol = Col("Oper Status", "operStatus", {cell: @Render("v", v == "Up" ? Tag("Up", "success") : Tag("Down", "danger"))})
certCol = Col("Certification", "huaweiCertified", {cell: @Render("v", v == "已认证" ? Tag("Certified", "success") : Tag("Uncertified", "warning"))})
