root = VLayout([heatmapTitle, heatmapCard])
heatmapTitle = Text("Alert Frequency Heatmap (Hour vs Day of Week)", "default")
heatmapCard = Card([heatmapHeader, heatmapChart])
heatmapHeader = CardHeader("Alert Frequency by Hour and Day", "Color intensity indicates number of alerts")
heatmapChart = HeatmapChart(data.xLabels, data.yLabels, data.values)