root = VLayout([regionSelector, infoText])
regionSelector = HLayout([label, select])
label = Text("Select Region:")
select = Select(data.options, data.defaultValue)
infoText = Text("Current selection: North America (default)")