root = VLayout([tableCard])
tableCard = Card([tableHeader, employeeTable])
tableHeader = CardHeader("Employee Directory", "Sortable salary and formatted join dates")
employeeTable = Table(columns, rows)
columns = [nameCol, salaryCol, dateCol]
nameCol = Col("Name", "name")
salaryCol = Col("Salary", "salary", {sortable: true})
dateCol = Col("Join Date", "joinedAt", {format: "date"})
rows = data.employees