root = VLayout([tableCard])
tableCard = Card([tableHeader, salesTable])
tableHeader = CardHeader("Regional Sales Breakdown", "Revenue by region with last update")
salesTable = Table([regionCol, revenueCol, updatedCol], data.report.breakdown)
regionCol = Col("Region", "region")
revenueCol = Col("Revenue", "revenue", {format: "date"})
updatedCol = Col("Last Updated", "updatedAt", {format: "dateTime"})