root = VLayout([tableCard])
tableCard = Card([employeeTable], "card", "standard", {title: "Employees", subtitle: "Sortable salary and formatted join dates"})
employeeTable = Table([nameCol, salaryCol, joinDateCol], data.employees)
nameCol = Col("Name", "name")
salaryCol = Col("Salary", "salary", {sortable: true})
joinDateCol = Col("Join Date", "joinedAt", {format: "date"})