root = VLayout([tabs])
tabs = Tabs([overviewTab, settingsTab])
overviewTab = {value: "overview", label: "Overview", content: [overviewContent]}
overviewContent = VLayout([overviewTitle, overviewDesc])
overviewTitle = Text("Welcome to the Dashboard", "large")
overviewDesc = Text("This is the overview tab where you can see a summary of your data.")
settingsTab = {value: "settings", label: "Settings", content: [settingsContent]}
settingsContent = VLayout([settingsTitle, settingsDesc])
settingsTitle = Text("Application Settings", "large")
settingsDesc = Text("Configure your preferences and options here.")