root = VLayout([tabsContainer])
tabsContainer = Card([tabs])
tabs = Tabs([overviewTab, settingsTab])
overviewTab = {value: "overview", label: "Overview", content: [overviewContent]}
overviewContent = VLayout([overviewTitle, overviewText])
overviewTitle = Text("System Overview", "default")
overviewText = Text("Welcome to the dashboard. This tab provides a high-level summary of your system status, performance metrics, and recent activity.", "default")
settingsTab = {value: "settings", label: "Settings", content: [settingsContent]}
settingsContent = VLayout([settingsTitle, settingsForm])
settingsTitle = Text("Configuration Settings", "default")
settingsForm = Form([themeField, notificationsField])
themeField = {label: "Theme", name: "theme", component: themeSelect}
themeSelect = Select([{label: "Light", value: "light"}, {label: "Dark", value: "dark"}, {label: "Auto", value: "auto"}], "light", false)
notificationsField = {label: "Enable Notifications", name: "notifications", component: notificationsToggle}
notificationsToggle = Select([{label: "On", value: true}, {label: "Off", value: false}], true, false)