root = VLayout([summaryCard])
summaryCard = Card([summaryHeader, summaryBody], "card", "full")
summaryHeader = CardHeader(data.summary.heading, "Q1 Financial Performance")
summaryBody = VLayout([growthText, detailText], "m")
growthText = Text("Growth: " + data.summary.growth, "large-heavy")
detailText = Text("**Q1 Results Summary**\n\nOur Q1 performance exceeded expectations with a solid **" + data.summary.growth + "** growth rate. Key drivers included strong product adoption, expanded market reach, and operational efficiencies. The team remains focused on sustaining this momentum through Q2 and beyond.", "default")